# Generated by Django 4.2.14 on 2024-07-25 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_birthdayprofile_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='birthday_profile',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='users.birthdayprofile'),
            preserve_default=False,
        ),
    ]
