# Generated by Django 4.2.14 on 2024-07-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_birthday_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
