version: '3'

services:
  app:
    image: birthday_wisher_application
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./scripts/wait-for-it.sh", "./scripts/run_app_development.sh"]
    restart: always
    #tty: true
    volumes:
      - ./:/code
    ports:
      - "8011:8000"
